// <auto-generated />
using Make_your_own_api.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Make_your_own_api.Migrations
{
    [DbContext(typeof(StarWarsDBContext))]
    partial class StarWarsDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Make_your_own_api.DAL.StarWarsFanDAL", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsAFan")
                        .HasColumnType("bit");

                    b.Property<string>("PeronalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StarWarsCharacterId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fans");
                });
#pragma warning restore 612, 618
        }
    }
}
